apiVersion: nais.io/v1
kind: Naisjob
metadata:
  labels:
    team: arbeidsforhold
    app: aareg-abonnering
  name: aareg-abonnering
  namespace: arbeidsforhold
spec:
  env:
    - name: JDK_JAVA_OPTIONS
      value: -XX:MinRAMPercentage=25.0 -XX:MaxRAMPercentage=75.0 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/heap.hprof
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 1Gi
